import {
  View,
  Text,
  StyleSheet,
  FlatList,
  RefreshControl,
  TouchableOpacity,
  Modal,
  ScrollView,
  Platform,
} from 'react-native';
import { useCallback, useMemo, useState } from 'react';
import useSWR from 'swr';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing, borderRadius, typography } from '@/lib/theme/colors';
import { swrFetcher } from '@/lib/api/client';
import type { Patch } from '@/lib/types';

const statusConfig = {
  applied: { label: 'Applied', color: colors.dark.success, icon: 'checkmark-circle' },
  pending: { label: 'Pending', color: colors.dark.warning, icon: 'time' },
};

interface PatchesResponse {
  patches: Patch[];
}

function formatDate(dateString: string) {
  const date = new Date(dateString);
  return date.toLocaleDateString();
}

function PatchCard({ patch, onPress }: { patch: Patch; onPress: () => void }) {
  const status = statusConfig[patch.status] || statusConfig.pending;

  return (
    <TouchableOpacity style={styles.patchCard} onPress={onPress}>
      <View style={styles.patchHeader}>
        <View style={[styles.statusBadge, { backgroundColor: `${status.color}20` }]}> 
          <Ionicons name={status.icon as keyof typeof Ionicons.glyphMap} size={14} color={status.color} />
          <Text style={[styles.statusText, { color: status.color }]}>{status.label}</Text>
        </View>
        <Text style={styles.patchDate}>{formatDate(patch.createdAt)}</Text>
      </View>

      <Text style={styles.patchFile} numberOfLines={1}>{patch.file}</Text>
      <Text style={styles.patchDescription} numberOfLines={2}>{patch.description}</Text>

      <View style={styles.patchStats}>
        <View style={styles.statChip}>
          <Ionicons name="add" size={14} color={colors.dark.success} />
          <Text style={styles.statText}>+{patch.linesAdded}</Text>
        </View>
        <View style={styles.statChip}>
          <Ionicons name="remove" size={14} color={colors.dark.destructive} />
          <Text style={styles.statText}>-{patch.linesRemoved}</Text>
        </View>
        <View style={styles.statChip}>
          <Ionicons name="git-branch-outline" size={14} color={colors.dark.mutedForeground} />
          <Text style={styles.statText}>Run {patch.runId.slice(0, 6)}</Text>
        </View>
      </View>
    </TouchableOpacity>
  );
}

export default function PatchesScreen() {
  const { data, isLoading, mutate } = useSWR<PatchesResponse>('/api/patches', swrFetcher);
  const [filter, setFilter] = useState<'all' | 'applied' | 'pending'>('all');
  const [selectedPatch, setSelectedPatch] = useState<Patch | null>(null);

  const patches = data?.patches || [];
  const filteredPatches = useMemo(
    () => (filter === 'all' ? patches : patches.filter((patch) => patch.status === filter)),
    [filter, patches]
  );

  const onRefresh = useCallback(async () => {
    await mutate();
  }, [mutate]);

  const filterOptions: Array<{ label: string; value: typeof filter }> = [
    { label: 'All', value: 'all' },
    { label: 'Applied', value: 'applied' },
    { label: 'Pending', value: 'pending' },
  ];

  return (
    <View style={styles.container}>
      <View style={styles.filterBar}>
        {filterOptions.map((option) => (
          <TouchableOpacity
            key={option.value}
            style={[
              styles.filterChip,
              filter === option.value && styles.filterChipActive,
            ]}
            onPress={() => setFilter(option.value)}
          >
            <Text
              style={[
                styles.filterChipText,
                filter === option.value && styles.filterChipTextActive,
              ]}
            >
              {option.label}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      <FlatList
        data={filteredPatches}
        keyExtractor={(item) => item.id}
        renderItem={({ item }) => (
          <PatchCard patch={item} onPress={() => setSelectedPatch(item)} />
        )}
        contentContainerStyle={styles.listContent}
        refreshControl={
          <RefreshControl
            refreshing={isLoading}
            onRefresh={onRefresh}
            tintColor={colors.dark.primary}
          />
        }
        ListEmptyComponent={
          <View style={styles.emptyState}>
            <Ionicons name="git-branch-outline" size={48} color={colors.dark.mutedForeground} />
            <Text style={styles.emptyTitle}>No patches yet</Text>
            <Text style={styles.emptyText}>Patches generated by PatchPilot will appear here.</Text>
          </View>
        }
      />

      <Modal
        visible={!!selectedPatch}
        animationType="slide"
        presentationStyle="pageSheet"
        onRequestClose={() => setSelectedPatch(null)}
      >
        {selectedPatch && (
          <View style={styles.modalContainer}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle} numberOfLines={1}>{selectedPatch.file}</Text>
              <TouchableOpacity onPress={() => setSelectedPatch(null)}>
                <Ionicons name="close" size={22} color={colors.dark.foreground} />
              </TouchableOpacity>
            </View>
            <ScrollView style={styles.modalContent}>
              <Text style={styles.modalDescription}>{selectedPatch.description}</Text>
              <View style={styles.diffContainer}>
                <Text style={styles.diffText}>{selectedPatch.diff}</Text>
              </View>
            </ScrollView>
          </View>
        )}
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.dark.background,
  },
  filterBar: {
    flexDirection: 'row',
    padding: spacing[4],
    gap: spacing[2],
    borderBottomWidth: 1,
    borderBottomColor: colors.dark.border,
  },
  filterChip: {
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2],
    borderRadius: borderRadius.full,
    backgroundColor: colors.dark.secondary,
  },
  filterChipActive: {
    backgroundColor: colors.dark.primary,
  },
  filterChipText: {
    fontSize: typography.sizes.sm,
    fontFamily: 'Inter-Medium',
    color: colors.dark.mutedForeground,
  },
  filterChipTextActive: {
    color: colors.dark.primaryForeground,
  },
  listContent: {
    padding: spacing[4],
    paddingBottom: spacing[10],
  },
  patchCard: {
    backgroundColor: colors.dark.card,
    borderRadius: borderRadius.xl,
    padding: spacing[4],
    marginBottom: spacing[3],
    borderWidth: 1,
    borderColor: colors.dark.border,
  },
  patchHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[2],
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1],
    paddingHorizontal: spacing[2],
    paddingVertical: spacing[1],
    borderRadius: borderRadius.full,
  },
  statusText: {
    fontSize: typography.sizes.xs,
    fontFamily: 'Inter-Medium',
  },
  patchDate: {
    fontSize: typography.sizes.xs,
    color: colors.dark.mutedForeground,
    fontFamily: 'Inter-Regular',
  },
  patchFile: {
    fontSize: typography.sizes.base,
    fontFamily: 'Inter-SemiBold',
    color: colors.dark.foreground,
  },
  patchDescription: {
    fontSize: typography.sizes.sm,
    color: colors.dark.mutedForeground,
    fontFamily: 'Inter-Regular',
    marginTop: spacing[1],
  },
  patchStats: {
    flexDirection: 'row',
    gap: spacing[2],
    marginTop: spacing[3],
    flexWrap: 'wrap',
  },
  statChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1],
    paddingHorizontal: spacing[2],
    paddingVertical: spacing[1],
    borderRadius: borderRadius.full,
    backgroundColor: colors.dark.secondary,
  },
  statText: {
    fontSize: typography.sizes.xs,
    color: colors.dark.mutedForeground,
    fontFamily: 'Inter-Regular',
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: spacing[16],
  },
  emptyTitle: {
    fontSize: typography.sizes.lg,
    fontFamily: 'Inter-SemiBold',
    color: colors.dark.foreground,
    marginTop: spacing[4],
  },
  emptyText: {
    fontSize: typography.sizes.sm,
    color: colors.dark.mutedForeground,
    fontFamily: 'Inter-Regular',
    textAlign: 'center',
    marginTop: spacing[2],
    maxWidth: 260,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: colors.dark.background,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing[4],
    borderBottomWidth: 1,
    borderBottomColor: colors.dark.border,
  },
  modalTitle: {
    flex: 1,
    fontSize: typography.sizes.base,
    fontFamily: 'Inter-SemiBold',
    color: colors.dark.foreground,
    marginRight: spacing[2],
  },
  modalContent: {
    padding: spacing[4],
  },
  modalDescription: {
    fontSize: typography.sizes.sm,
    color: colors.dark.mutedForeground,
    fontFamily: 'Inter-Regular',
    marginBottom: spacing[4],
  },
  diffContainer: {
    backgroundColor: colors.dark.secondary,
    borderRadius: borderRadius.lg,
    padding: spacing[4],
  },
  diffText: {
    fontSize: typography.sizes.xs,
    color: colors.dark.foreground,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
  },
});
